### ISSUE TITLE
Zakładka Partnerzy dla Sabiny

### ISSUE THREAD

**Issue by Dziabodo** [DrupalCampWroclaw/website#16]
Sabina domaga się zakładki partnerzy na stronie. Właśnie pouczyła mnei o potrzebie jej stworzenia:) Zrobie ją i wrzuce zmiany razem z poprawionym css. Zakładka ma wyglądać jak zakładka sponsorów. Zrobie to jako widok do content type partnerzy, widok będzie wyswietlał loga partnerów, które będa linkami do ich stron.

**Comment by grzegorzbartman** [comment]
w #2 jest propozycja mapy strony i umiejscowienie strony z partnerami. Jak to ma być na szybko to można dodać zwykłego noda typu Page i wstawić tam grafiki. Takie rozwiązanie powinno wystarczyć.

**Comment by grzegorzbartman** [comment]
Jaro już zaczął robić stronę statyczną, pogadaj z nim aby ustalić wygląd strony.

**Comment by Dziabodo** [comment]
ok

**Comment by grzegorzbartman** [comment]
Zamykam
