### ISSUE TITLE
Mapa strony

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website#2]
Przygotowanie mapy strony i listy funkcjonalności

**Comment by grzegorzbartman** [comment]
Propozycja mapy strony (nie wszystkie opcje obowiązkowe)

Home
People
-- Attendees
-- Speakers
-- Team
Place/Wroclaw
-- Location
-- Accomodation
Conference
-- Important dates
-- Program
-- Proposed Sessions
-- Accepted Sessions
-- Training
-- Special Tickets (food, special gadgets)
-- Special events/Social events
-- Code sprint
-- FAQ
-- Gallery (flickr example http://2013.drupalaton.hu/gallery)
-- Speakers resources
Sponsors
-- Diamond sponsor 1
-- Diamond sponsor 2
-- All sponsors
Job board
Contact

**Comment by MaciejLukianski** [comment]
Masz może plany co do tego jak wykonać poszczególne elementy strony? Łatwiej będzie się włączyć jak będzie dokładnie wiadomo co jak chcesz wykonać.

**Comment by grzegorzbartman** [comment]
Myslałem aby to tak zrobić:

People (może ten label zamienić na community) to 3 widoki z listą zdjęć użytkowników jak na https://prague2013.drupal.org/attendee Utworzymy w systemie role "team member" oraz "speaker" aby oddzielić tych użytkowników i wyświetlić ich na osobnych stronach. 
Profil użytkownika powinien mieć pola imię, nazwisko, organizacja, job title. Dla "team member" można dodać dodatkowe pole tekstowe, gdzie można wpisać czym dana osoba się zajmuje podczas konferencji. 

Place/Wroclaw - to strony tekstowe (node page) z opisem Wrocławia, mapkami, zdjęciami, itp.

Conference: Proposed Sessions/Accepted session - views na podstawie rodzaju zawartości Session, tabela.

Conference: pozostałe podstrony - strony statyczne (node page)

Sponsors - strony statyczne (page) albo robimy rodzaj zawartości Sponsor i za pomocą views wyświetlamy te strony, dodajemy taxonomy z typem sponsora.

Job board - strona statyczna lub rodzaj zawartości Job, opcjonalnie powiązany z nodem typu sponsor, jesli go zrobimy

Contact - formularz kontaktowy + dane kontaktowe

Jeśli macie propozycje jak to inaczej zrobić to piszcie. Uważam, że powinniśmy wybierać takie rozwiązania aby poszczególne podstrony w miarę szybko postawić online i sobie nie komplikować pracy skomplikowaną strukturą danych.

**Comment by grzegorzbartman** [comment]
Zmiana mapy - dochodzi osobna strona dla partnerów/patronów medialnych 

Home
People
-- Attendees
-- Speakers
-- Team
Place/Wroclaw
-- Location
-- Accomodation
Conference
-- Important dates
-- Program
-- Proposed Sessions
-- Accepted Sessions
-- Training
-- Special Tickets (food, special gadgets)
-- Special events/Social events
-- Code sprint
-- FAQ
-- Gallery (flickr example http://2013.drupalaton.hu/gallery)
-- Speakers resources
Sponsors & Partners
-- Diamond sponsor 1
-- Diamond sponsor 2
-- All sponsors
-- Media partner
Job board
Contact
